MysqlHOST: 'null'
MysqlDATABASE: 'null'
MysqlUSER: 'null'
MysqlPASSWORD: 'null'
MysqlPORT: 'null'
TittleTOP: ''
TittleBOTTOM: ''
TablistTOP: ''
TablistBOTTOM: ''
debug: 'false'
discordbot: 'false'
elevators: 'true'
firealarms: 'true'
trafficsystem: 'false'
signTranslateColors: 'true'