name: World1-6Essentials
version: 1.0
author: Andrew121410
main: com.andrew121410.mc.world16essentials.World16Essentials
api-version: 1.18

depend:
  - World1-6Utils
softdepend:
  - EssentialsX

commands:
  World1-6Essentials:
  bed:
  commandblock:
  day:
  debug1-6:
  feed:
  fly:
  heal:
  night:
  ram:
  spawn:
  echest:
  setspawn:
  sign:
  colors:
  afk:
  fs:
    aliases:
      - flyspeed
      - fspeed
  isafk:
  testee1:
  food:
  back:
  tpa:
  tpaccept:
  tpdeny:
  broadcast:
  god:
  emsg:
  waitdo:
  runcommands:
  wformat:
  xyzdxdydz:
  workbench:
  delhome:
  home:
  homelist:
    aliases:
      - homes
  sethome:
  lastjoin:
  warp:
    aliases:
      - to
  setwarp:
  delwarp:
  powertool:
  unsafenchant:
  commandblockfind:
  sudo:
  shouldkeepspawnchunksloaded:
  countallentities:

  gmc:
    aliases:
      - gm1
  gms:
    aliases:
      - gm0
  gmsp:
    aliases:
      - gm3
  gma:
    aliases:
      - gm2

permissions:
  world16.tpa:
    description: Allows to do tpa
    default: true
  world16.tpaccept:
    description: Allows to do tpaccept
    default: true
  world16.tpdeny:
    description: Allows to do tp deny
    default: true
  world16.afk:
    description: Allows to do afk
    default: true
    children:
      world16.afk.other: true
  world16.back:
    description: Allows to do back
    default: true

  world16.back.all:
    description: Allows to do every back command
    default: true
    children:
      world16.back: true
      world16.back.death: true
      world16.back.tp: true

  world16.bed:
    description: Allows to do bed
    default: op
  world16.broadcast:
    description: Allows to do broadcast
    default: op
  world16.colors:
    description: Allows to do colors
    default: true
  world16.commandblock:
    description: Allows to do commandblock
    default: op
  world16.day:
    description: Allows to do day
    default: op
  world16.debug:
    description: Allows to do debug
    default: op
  world16.echest:
    description: Allows to do echest
    default: op
  world16.feed:
    description: Allows to do feed
    default: op
  world16.fly:
    description: Allows to do tpa
    default: op
  world16.fs:
    description: Allows to do flight speed
    default: op
  world16.gma:
    description: Allows to do gma
    default: op
  world16.gmc:
    description: Allows to do gmc
    default: op
  world16.gms:
    description: Allows to do gms
    default: op
  world16.gmsp:
    description: Allows to do gmsp
    default: op
  world16.god:
    description: Allows to do god
    default: op
  world16.heal:
    description: Allows to do heal
    default: op
  world16.isafk:
    description: Allows to do isafk
    default: true
  world16.night:
    description: Allows to do night
    default: op
  world16.ram:
    description: Allows to do ram
    default: op
  world16.setspawn:
    description: Allows to do setspawn
    default: op
  world16.sign:
    description: Allows to do sign
    default: op
    children:
      world16.sign.color: true
  world16.spawn:
    description: Allows to do spawn
    default: true
  world16.msg:
    description: Allows to do msg
    default: op
  world16.waitdo:
    description: Allows to do waitdo
    default: op
  world16.runcommands:
    description: Allows to do runcommands
    default: op
  world16.wformat:
    description: Allows to do wformat
    default: op
  world16.xyzdxdydz:
    description: Allows to do xyzdxdydz
    default: op
  world16.workbench:
    description: Allows to do workbench
    default: true
  world16.home:
    description: Allows to do home commands
    default: true
  world16.home.op:
    description: Allows to do op home commands
    default: true
  world16.lastjoin:
    description: Allows to do lastjoin
    default: true
  world16.warp:
    description: Allows to do warp
    default: true
  world16.setwarp:
    description: Allows to do setwarp
    default: true
  world16.delwarp:
    description: Allows to do delwarp
    default: true
  world16.powertool:
    description: Allows to do powertool
    default: op
  world16.unsafenchant:
    description: Allows to do unsafenchant
    default: op
  world16.commandblockfind:
    description: Allows to do commandblockfind
    default: op
  world16.sudo:
    description: Allows you to do sudo
    default: op
  world16.shouldkeepspawnchunksloaded:
    description: Allows you to do shouldkeepspawnchunksloaded
    default: op
  world16.countallentities:
    description: Allows you to do countallentities
    default: op