name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Chmod Gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 21 # https://github.com/actions/setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle # https://github.com/gradle/gradle-build-action -> https://github.com/gradle/actions
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Generate sha256sum
        run: sha256sum build/libs/World1-6Essentials.jar >> hash.txt

      - name: Deploy Release With Artifact
        uses: "softprops/action-gh-release@v2.0.4" # https://github.com/softprops/action-gh-release old version: https://github.com/marvinpinto/action-automatic-releases
        with:
          tag_name: "latest"
          make_latest: true
          prerelease: false
          generate_release_notes: true
          files: |
            build/libs/World1-6Essentials.jar
            hash.txt